# Generated by Django 2.2.2 on 2019-06-21 10:37

from django.db import migrations, models

import main.validators


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_auto_20190619_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='topics_following',
            field=models.ManyToManyField(related_name='followers', to='main.Topic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'},
                                   help_text='Required. 16 characters or fewer. Letters, digits and @/./+/-/_ only.',
                                   max_length=16, primary_key=True, serialize=False, unique=True,
                                   validators=[main.validators.UsernameValidator()], verbose_name='username'),
        ),
    ]
